version: "3.8"
services:
  redbot:
    image: ghcr.io/ksurl/redbot
    container_name: redbot
    # 1st run setup needs to be run manually by attaching to container as runtime user
    #command: ['tail', '-f', '/dev/null' ]
    environment:
      - PUID=1000
      - PGID=1000
      - INSTANCE=docker # change to your instance name
    volumes:
      - data:/config # set path according to redbot-setup 1st run
    restart: unless-stopped

volumes:
  data: